BritishGeologicalSurvey/etlhelper

.travis.yml
Should:
-  [x] Install the requirements
-  [x] Install the package
-  [x] Run the unit tests, in the two most recent versions of Python.
=> WIP: Basic travis CI script

README.md
Fixes a broken link in the README
=> fix broken pypi link

README.md, etlhelper/__init__.py, etlhelper/etl.py, test/integration/etl/test_etl_logging.py
This merge request allows central configuration of `etlhelper` and provision of useful logging messages.
+ [ ] Use instructions from README to configure logging on an ETL script of your own
+ [ ] Confirm output for DEBUG and INFO levels
+ [ ] Confirm all unit and integration tests pass as described in CONTRIBUTING.md
Closes #7
=> Improve logging

.gitignore, etlhelper/db_params.py, requirements.txt, test/unit/test_db_params.py
=> __setattr__ special method

etlhelper/etl.py, test/integration/etl/test_etl_extract.py
=> Catch StopIteration raised by empty fetchone()

etlhelper/setup_oracle_client.py
=> Remove old comments from setup_oracle_client

README.md
Add Airflow recipe.
+ [x] Check it makes sense
+ [x] Confirm URLs work
=> Add Airflow recipe

README.md, test/integration/etl/test_etl_transform.py
This merge request adds an example of using a dict_row_factory and modifying individual columns with a transform function to the README.  We did this kind of workflow last week and it would be helpful to have it documented.  There is also an integration test added to confirm that this syntax works.
+ [x] Read the `Transform` section of the README and confirm that it makes sense
+ [x] Run the tests and confirm that they cover this type of workflow
=> Add explanation of in-place dictionary transform

.gitlab-ci.yml, requirements.txt
Adds a wheel version of the package.
Confirm via internal CI that it worked.
=> Distribute as wheel 2

etlhelper/setup_oracle_client.py, test/integration/test_setup_oracle_client.py
resolve #76 
urllib.request captures URLError and raises it for higher try/except block in setup_oracle_client
=> make setup_oracle_clientfail gracefully with useful log message

README.md
Replacing "between databases" with "into and out of" better highlights how ETL Helper can be used for more than just db to db transfers.
=> Change summary quote to _into and out of_

README.md, etlhelper/etl.py, etlhelper/exceptions.py, test/integration/etl/test_etl_load.py, test/unit/test_etl.py
This merge request closes #133.  It performs validation on table and column names that are passed to the `load` function.  This prevents malicious code being inserted into the auto-generated SQL.
+ [ ] Run test suite and confirm that examples work
=> No bobby tables

CODE_OF_CONDUCT.md, README.md, setup.py
This merge request makes minor changes to the repository.
Adding a CODE_OF_CONDUCT will increase the quality score of the project, e.g. at https://snyk.io/advisor/python/etlhelper.
Adding ETL to the description will make it easier to find on pypi searches, e.g. https://pypi.org/search/?q=etl (closes #131).
=> Repo tweaks

etlhelper/db_helpers/sqlite.py
This pull request merges the SQLite test fix authored by @ximenesuk into the `for_v1` branch.
I have checked the tests and they now complete with no errors.
=> Change column type to lowercase

README.md, etlhelper/__init__.py, etlhelper/etl.py, test/integration/etl/test_etl_extract.py
This merge request removes the `dump_rows` function.
Closes #152
=> Remove dump_rows

.dockerignore, .github/workflows/test.yml, CONTRIBUTING.md, Dockerfile, README.md, etlhelper/db_helpers/db_helper.py, etlhelper/db_helpers/mssql.py, etlhelper/etl.py, etlhelper/utils.py, pyproject.toml, requirements-dev.txt, test/conftest.py, test/integration/db/test_mssql.py, test/integration/db/test_oracle.py, test/integration/db/test_sqlite.py, test/integration/etl/test_etl_extract.py, test/integration/etl/test_etl_load.py, test/integration/etl/test_etl_logging.py, test/integration/etl/test_etl_transform.py
This merge request sets the default row factor to `dict`.
This closes #153
=> 153 set default row factory to as dict

.github/workflows/test.yml, test/integration/db/test_mssql.py, test/integration/db/test_oracle.py
This merge request runs all the tests in CI.
It closes #177
=> 177 run postgresql integration tests in ci

.flake8, etlhelper/etl.py, etlhelper/types.py, requirements-dev.txt
This branch adds type hints to the `etl.py` module.
=> More type hints

docs/code_demos/recipes/csv_files.py
Updates the imports on csv_files.py in docs
=> Update csv_files.py imports

docs/code_demos/utilities/enable_logger.py, docs/index.rst, pyproject.toml
This merge request removes some of the pre-production notes and updates the documentation.
=> Pre release tweaks

docs/code_demos/recipes/database_to_api.py, docs/etl_functions/extract.rst, docs/recipes/database_to_api.rst
additional info and inline comments about the database to API recipe
=> Database to API / NoSQL comments
