BritishGeologicalSurvey/etlhelper

.gitlab-ci.yml, README.md, bin/run_tests_for_developer.sh, etlhelper/db_helpers/mssql.py, etlhelper/db_helpers/oracle.py, etlhelper/db_helpers/postgres.py, etlhelper/db_params.py, test/conftest.py, test/integration/db/test_oracle.py, test/unit/test_db_helpers.py, test/unit/test_db_params.py
These commits allow `DbParams.from_environment()` to take advantage of the new, flexible way to specify required parameters.
+ [x] manually define a database connection from environment variables to confirm that it works
+ [x] confirm all tests work locally, using environment variables from CI environment
=> Params from env

README.md, bin/run_tests_for_developer.sh, etlhelper/connect.py, etlhelper/db_helper_factory.py, etlhelper/db_helpers/__init__.py, etlhelper/db_helpers/db_helper.py, etlhelper/db_helpers/sqlite.py, etlhelper/etl.py, test/integration/db/test_sqlite.py, test/unit/test_db_helpers.py
SQLite databases have different connection string syntax and cursors to
previous database types.  To incorporate this:
+ DbHelper now has cursor() method to allow modified SQLite cursor,
which can be used as context manager, to be returned
+ etl functions user helper.cursor() to obtain a cursor
+ password_variable is now optional on connect methods
Unit tests for database helpers were also refactored for clarity.
+ [ ] Use an IPython session to create a SQLite database of your own and run queries against it
+ [ ] Confirm that unit and integration tests run
Closes #4
=> Add SQLite helper

.gitlab-ci.yml, test/integration/etl/test_etl_logging.py
The logging improvements added in #9 were merged but they failed the tests in GitLab CI.  This is because the host for the database server used in the integration tests was IP address instead of being `localhost`.  The resulting log messages did not match.
This PR fixes the tests so that they replace the hostname recorded in the logs with ??? and updates the expected text string accordingly.
You can't really test this, but if you look in the GitLab CI logs you can see that the pipeline on the `verbose-tests` branch passed.  This is the same code as the current branch.
=> Logging test fix

.gitlab-ci.yml
Automates the release cycle (though with a final manual step on gitlab until the issue of having
```
only:
- tags
- master
```
is resolved.
=> Automate releases

CONTRIBUTING.md, Dockerfile, etlhelper/db_params.py, test/conftest.py, test/integration/db/test_oracle.py
Integration tests began failing in GitLab since the CI process began installing pytest version 5.3.1.  Part of the parameterised test system tries to access the `__name__` attribute of DbParams classes and crashes because a KeyError is raised.  In fact, DbParams should raise an AttributeError.
This pull request makes the fix (see commit messages for more details) and does a bit of spring cleaning.
=> Fix integration tests

.gitlab-ci.yml, Dockerfile
These changes ensure that git is available in the container used for packaging so that the tags can be read.  See GitLab CI history for details.
Closes #14 
Merge, tag and check for a release.
=> Packaging fix

etlhelper/db_params.py, test/integration/test_dbparams.py, test/unit/test_db_params.py
This pull request adds a `copy()` function to DbParams classes.  It overrides the built-in copy function that previously existed as a consequence of DbParams being derived from a dictionary.  That version would return a dictionary; this one returns a DbParams class.
Note: this should only be merged after the `dbparams-fix` branch has been merged as it is built on top of it.
+ [x] Check tests and output
+ [x] In an IPython session, create a DbParams object, copy it and confirm that it has correct attributes and that modifying it doesn't modify the original.
=> Add copy() function to DbParams

test/conftest.py, test/integration/test_dbparams.py
db_params.is_reachable() failed in CI because test postgres database is at postgis and not at localhost.  This merge fixes this by using test fixture testpgdb_params instead.  The fixture was updated as the hostname changing didn't previously work.  Now uses dictionary.update() syntax.
+ [x] check internal gitlab pipeline to confirm that tests pass
+ [x] run tests locally and confirm they pass
=> Dbparams copy fix

etlhelper/etl.py, requirements.txt
This merge request add a deprecation warning to `executemany` as the parameter order will change in future. This is related to #28, which we are not merging yet.
=> Add deprecation warning for executemany param order

.gitignore, README.md, etlhelper/__init__.py, etlhelper/etl.py, requirements.txt, test/integration/etl/test_etl_extract.py
This merge request adds the new methods `fetchone`, `fetchmany` and `fetchall` to etlhelper.  This makes it more consistent with the methods on a DBAPI 2 style cursor.  Closes #29.
As part of this development, the integration tests for select methods were updated.  Repeated, similar tests for transform and parameters for `get_rows` and `dump_rows` were consolidated.  `print` was set as the default function to `dump_rows`.
+ [x] try each of the new functions by hand, including different `size` values for `fetchmany`
+ [x] try `dump_rows` with and without defining an `output_func`
=> 29 add fetch methods

etlhelper/setup_oracle_client.py, test/integration/test_setup_oracle_client.py
This merge request adds functions for `install_libraries` and `symlink_libraries`.  It also stubs out an `install_instantclient` function based on the pseudocode in Issue #2.
There is an integration test to prove that they work.  This test runs against `install_instantclient` and should be extended as each of the sub-functions are fleshed out.
Note that I have tried to use Pathlib where possible for file operations.  It seems like a good way to go.
=> Refactor setup script install func

Dockerfile, bin/run_tests_for_developer.sh, etlhelper/setup_oracle_client.py, pytest.ini, test/integration/db/test_oracle.py, test/integration/test_setup_oracle_client.py, test/unit/test_setup_oracle_client.py
This merge request makes the zip_location an optional parameter without it necessarily being named.  This makes the syntax compatible with the previous versions so that Dockerised tests work.  Making this change revealed problems with the code that were only visible when running the full integration test suite.  These changes were made now.
Note that our new install script will break CI pipelines because the LD_LIBRARY_PATH that drivers are installed to is different.  This path is hard-coded into various Docker containers.
This merge contributes to #2
=> Fixes for dockerised tests

README.md, etlhelper/etl.py, etlhelper/row_factories.py, test/integration/etl/test_etl_extract.py, test/unit/test_row_factory.py
This makes the code consistent internally and with other Python modules
e.g. sqlite3.
This is a breaking change.
Closes #43.
+ [x] Run a SELECT query against a database and confirm different row_factories work.
=> Replace rowfactory with row_factory

README.md, etlhelper/db_helpers/postgres.py, etlhelper/etl.py, test/integration/etl/test_etl_load.py
Reversing the parameter order makes executemany(query, conn, rows)
consistent with existing execute(query, conn).
This is a breaking change.
This change extends #28 by updating tests and documentation.
=> Change parameter order for executemany

etlhelper/db_helpers/db_helper.py, etlhelper/db_helpers/mssql.py, etlhelper/db_helpers/oracle.py, etlhelper/db_helpers/postgres.py, etlhelper/db_helpers/sqlite.py, etlhelper/etl.py, test/integration/db/test_oracle.py, test/integration/db/test_sqlite.py, test/unit/test_db_helpers.py
The DBAPI 2.0 specification allows different placeholder formats to be used for parameters in queries e.g. `?`, `:name`, `%s`.  It can be confusing when moving between different database drivers, as they use different ones.  The `paramstyle` attribute of the driver defines which kind should be used.
This merge request adds the `paramstyle` to the DbHelper objects so that is can be checked.  It also updates the error messages in the ETL functions so they display the expected paramstyle.  This will make debugging easier.
Closes #3
+ [ ] Confirm tests pass
+ [ ] Write a bad query and confirm paramstyle is displayed in message
=> Paramstyle fix

etlhelper/setup_oracle_client.py
This commit removes comments from `setup_oracle_client` that have become out of date.  In particular, they reference a way of checking the drivers are installed for Windows.  We don't support installing for Windows at the moment.
Closes #44
n/a
=> Remove old comments from setup_oracle_client

.coveragerc, Dockerfile, etlhelper/setup_oracle_client.py, test/integration/test_setup_oracle_client.py, test/unit/test_setup_oracle_client.py
Adds a `--reinstall` optional flag that reinstalls the Oracle drivers, for example to deal with an aborted installation or to force a reinstall, or to install a different version of the already installed drivers. Extra tests in test suite to verify behaviour. 
Closes #2, #54, #60
=> Reinstall option flag

.gitlab-ci.yml
This merge requests sets extra environment variables in the Docker container used to run the integration tests within BGS.  These are needed for the new MS SQL tests.
=> Update MSSQL env vars for internal CI Docker tests

etlhelper/etl.py, test/integration/etl/test_etl_extract.py
This fix had already been submitted by @metazool and merged by @dvalters, but somehow it isn't in the `main` branch now.  This pull request adds it again.
https://github.com/BritishGeologicalSurvey/etlhelper/pull/42
=> Catch StopIteration raised when fetchone() is empty

etlhelper/__init__.py, etlhelper/db_params.py, test/unit/test_db_params.py
This merge request adds `connect`, `get_connection_string` and methods `get_sqlalchemy_string`, plus a `paramstyle` property to the DbParams class.
Closes #65 
Closes #66
=> Add connect module functions to DbParams

README.md
This merge request fixes a typo in the ETL script.  The DELETE sql was using Oracle syntax, now replaced with PostrgreSQL syntax.
=> Fix typo in ETL template

.dockerignore, etlhelper/db_helpers/db_helper.py, etlhelper/db_helpers/mssql.py, etlhelper/db_helpers/oracle.py, etlhelper/db_helpers/postgres.py, etlhelper/setup_oracle_client.py, test/integration/db/test_sqlite.py
Hi!
Learned about `etlhelper` via Twitter today. Unfortunately didn't have much time to experiment with it today. At my previous role in my current job, I had to manage some ETL jobs (Perl + Make, Talend, and orchestrated by Jenkins or triggered manually).
I will drop a message later to a co-worker who is responsible for those jobs now, to let her know about `etlhelper`. It sounds like a very good tool for the kind of jobs we have, though not sure if she'd have the time (and courage, some of that Perl code hasn't been touched in years) to upgrade it.
Had a look at the code, and it looks really great! Very simple and well documented. :+1: :clap: 
This PR just fixes some docstring params, a couple typos, and also added a [dockerignore](https://docs.docker.com/engine/reference/builder/#docker …
=> Typos comments and dockerignore

etlhelper/db_helpers/db_helper.py, etlhelper/db_helpers/mssql.py, etlhelper/db_helpers/oracle.py, etlhelper/db_helpers/postgres.py, etlhelper/db_helpers/sqlite.py, etlhelper/db_params.py, etlhelper/setup_oracle_client.py, test/integration/db/test_sqlite.py, test/integration/test_dbparams.py, test/unit/test_db_helpers.py, test/unit/test_db_params.py
This merge request changes the console output of `etllhelper` so that:
+ Messages raised when creating a `DbParams` object for which no driver is installed are raised as `UserWarning` instead of print.
+ These messages are standardised across different db_helper classes.
+ Messages printed prior to a `sys.exit()` are raised via `logging.error`
This should result in clean `stdout`, with the `print()` only ever used to return the file path of the ld_library_update script.  All other messages go to `stderr`.  If required, the UserWarning can be turned off e.g. via environment variable `PYTHONWARNINGS=ignore.
Closes #27.
https://stackoverflow.com/questions/14463277/how-to-disable-python-warnings
During this work, it was noticed that it was possible to create DbParams objects with invalid sets …
=> Warn on no driver

README.md
This explains how keyword arguments can be passed to connect.  We have found the need to set the encoding with internal Oracle databases in real projects.
=> Explain connect kwargs and use in setting encoding

README.md
This merge requests adds a new recipe to README.md.  It shows how to post data to a REST API.  The script is modified from code we wrote to post data to the SensorThingsAPI.
This is not a code change, so the purpose of the merge review is to see if there can be improvements to the wording.  However, the script does work if you want to test it.
1. Spin up an ElasticSearch container `docker run -d --rm --name elasticsearch -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:7.9.2`
2. Create a file called `db.py` that creates a DbParams class called ORACLE_DB which corresponds to the BGS development database
3. Save the example code as `copy_samples.py`
4. Replace "samples" in the select query with the Oracle dictionary of your choice
5. Increase the time range in the …
=> Add API posting recipe

test/integration/test_setup_oracle_client.py
When I run tests from my home internet, the `test_zipfile_bad_url` test fails because my ISP returns an HTML file instead of an NXDOMAIN error.  I don't want to change the test, because I think the problem is my ISP, but I've added an extra comment as a reminder for when it happens again.
n/a
=> Add comment on DNS hijacking test failure

README.md, etlhelper/db_helper_factory.py, etlhelper/db_helpers/mssql.py, test/integration/db/test_mssql.py, test/unit/test_db_helpers.py
See #86 for underlying issue and discussion.
The flag to use `fast_executemany` is an optional keyword argument on the overridden `connect` method of the `MSSQLDbHelper`, the default value is True. In order to persist the attribute, if it is set, an `@lru_cache` has been used for in the `DbHelperFactory` for `DBHelper` instances.
The `MSSQLDbHelper` `executemany` method is also overridden to try to use this attribute and fallback on False if there is an error. The error will arise if deprecated column types `text` and `ntext` are used.
The expanded integration tests should cover all the above cases and the problem of monkeypatching cached helpers has been added to the unit tests.
+ [x] Check code changes look reasonable
+ [x] Tests all pass
+ [x] README section makes sense
Closes #86
=> Use fast_executemany option of pyODBC for MS SQL Server access

test/integration/etl/test_etl_logging.py
This merge request makes prevents the logging tests from failing incorrectly if PostgreSQL is running on a different port to 5432.
Closes #102
=> Modify logging test to handle non-standard port

README.md, etlhelper/db_helpers/postgres.py, etlhelper/etl.py, etlhelper/exceptions.py, test/conftest.py, test/integration/db/test_mssql.py, test/integration/db/test_oracle.py, test/integration/db/test_sqlite.py, test/integration/etl/test_etl_extract.py, test/integration/etl/test_etl_load.py, test/integration/etl/test_etl_logging.py, test/integration/etl/test_etl_transform.py, test/unit/test_db_helpers.py
This merge request add the `on_error` parameter to `executemany`.  If a chunk raises an error then it will be retried as individual rows and the failing rows and their exceptions collected into a list.  The `on_error` function is then called on the list.
This provides a flexible way for users to handle failing rows in "real" time, as any function can be used.  The updated [README.md](README.md) has details.
Closes #91, which has much more discussion (and also #113, which is a bug-fix)
The changes also include making `chunk_size` a named parameter on many of the functions.  This makes it more convenient to change, rather than having to modify a module-level constant.
+ [x] Confirm that tests pass locally
To experiment, use the script below to test out inserting data to a SQLite database. …
=> Add on_error handling to executemany and related methods

etlhelper/etl.py, test/integration/etl/test_etl_load.py
The existing check for an empty set of rows (`if not rows`) doesn't
catch an empty generator.
=> Add test for empty generator

README.md, etlhelper/__init__.py, etlhelper/abort.py, etlhelper/etl.py, etlhelper/exceptions.py, test/integration/etl/test_abort.py
This pull request adds an `abort_etlhelper_threads()` function that allows jobs to be cancelled from other threads.  This is useful for GUI applications that use ETLHelper.  It closes #124.
The abort code is relatively simple and the test code is actually more tricky.  It needs to use the ThreadPoolExecutor to run the jobs and capture exceptions that they raise.  They comments and description should make sense, but please modify if they don't.
+ [x] Confirm that all tests pass
=> Abort function

etlhelper/etl.py, test/unit/test_etl.py
This is a minor fix to allow schema-qualified table names e.g. "public.my_table" to pass validation.
=> Allow schema-qualified names in validate_identifier

etlhelper/etl.py, test/integration/etl/test_etl_transform.py
This is a minor update to apply `validate_identifier` to the table name passed to `copy_table_rows`.
=> Validate table name in copy_table_rows

etlhelper/__init__.py
This merge request fixes a small issue which helps code editors to provide productivity improvements for `etlhelper.row_factories`.
Currently, `etlhelper.row_factories` is accessed directly from `etlhelper/row_factories.py`, it is not imported in any `__init__` files. Whilst the submodule is accessible, code editors (e.g., VSCode) cannot provide productivity improvements for this submodule:
To solve this, the following has been done:
- Add `from etlhelper import row_factories` to `etlhelper/__init__.py`
=> Add row_factories import to __init__

README.md, docs/index.rst, etlhelper/__init__.py, etlhelper/etl.py, test/integration/etl/test_etl_extract.py
This merge request deprecates the function `fetchmany` as specified by issue #154.
Closes #154
=> 154 deprecate fetchmany

etlhelper/db_helpers/sqlite.py
This merge request updates the table info returned by SQLite to ensure that the `type` is in lower case.  A recent change to `sqlite3` changed the response, causing our test suite to fail.
=> Change column type to lowercase

README.md, etlhelper/__init__.py, etlhelper/etl.py, test/integration/db/test_mssql.py, test/integration/db/test_oracle.py, test/integration/db/test_sqlite.py, test/integration/etl/test_etl_extract.py, test/integration/etl/test_etl_load.py, test/integration/etl/test_etl_transform.py
The function `get_rows` has been deprecated in favour of `fetchall`. This change has been made across the code, tests and documentation.
Closes #176
=> Deprecate get rows

README.md, etlhelper/db_helpers/oracle.py, test/integration/db/test_oracle.py
This merge request updates the default behaviour of the `oracledb` driver so that LOB data are returned as native Python strings/bytes.
It includes updated documentation and a test to confirm the mechanism for switching between string/bytes and LOB return types.  It also confirms that LOBs longer than 4000 characters are returned intact.
Closes #110
+ [x] Confirm that test suite passes
Ideally, we would also run code from this branch against internal BGS spatial data scripts to confirm that they still work.
=> Read LOBs as string/bytes instead of streaming

etlhelper/etl.py
This small PR updates the docstrings in `etl.py` to reflect the use of type hints. It cherry-picks e6d600d, to reuse the work done by @leorudczenko, and then modifies that commit to reflect code and type hint changes.
=> Etl post type hint docs

.github/workflows/gh-pages.yml
The current `sphinx` build uses Python `3.8`, which is older than the minimum version for `etlhelper` (`3.9`). This meant that the docs could not understand our typehints, which then caused the docs to fail to build some pages.
=> Bump ubuntu version and use python 3.10

README.md
Although there are releases in GitHub, not all of them have been released to PyPI.
=> Use PyPI list for published releases

etlhelper/db_helper_factory.py
This pull request adds a missing typehint to the `db_helper_factory.py` script.
=> added type hint to connection types in db_helper_factory

test/integration/db/test_mssql.py
The SQL Server implementation of  `executemany` takes advantage of a cursor flag `fast_executemany` to increase the speed of bulk queries ten-fold. However, some circumstances cause this method to fail, in particular tables with deprecated column types such as `TEXT` and `NTEXT`. The  `executemany` method catches the `MemoryError` raised in such cases, issues a warning and tries the query again with `fast_executemany` set to `False`.
The test for this special case checks for the warning. Since moving to `msodbcsql18`, locally this test still passes, but on the BGS internal gitlab CI pipeline, using the same docker image, it fails as no warning is issued. So far the reason for this hasn't been found and using a mock was ruled out as it would effectively only test the mock. So, in order to …
=> Skip test that passes locally but fails in CI

.github/workflows/test.yml
This merge request applies a small change to run the pipeline tests against these newer Python versions:
-  `3.12`
- `3.13`
This means our tests are now run against Python version `3.9` through to `3.13` successfully.
=> Run tests on newer Python versions

etlhelper/db_helpers/oracle.py, test/unit/test_db_helpers.py
This merge request applies the change specified in #215, and makes an appropriate adjustment to the tests.
=> 215 make oracledbhelperget sqlalchemy connection string use oracle+oracledb instead of oracle
